name: Deploy JAPR Journal Website to the live server
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploying:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/html/secureops_journal
            sudo git pull origin main


  optimising:
    runs-on: ubuntu-latest
    needs: deploying
    steps:
      - name: SSH into EC2 instance and optimize assets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /var/www/html/secureops_journal
            composer install --no-interaction --optimize-autoloader

            # Run DB migration just in case of new Migration file
            php artisan migrate:fresh --seed
            composer dump-autoload
